services:
  rustfs:
    image: rustfs/rustfs:1.0.0-alpha.85
    container_name: rustfs
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data/rustfs:/data
    environment:
      - RUSTFS_ACCESS_KEY=admin
      - RUSTFS_SECRET_KEY=password
    command: >
      --access-key admin --secret-key password /data
    networks:
      - docker_net
    healthcheck:
      test: [ "CMD-SHELL", "curl -sS http://localhost:9001 || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 5

  rustfs-init:
    image: minio/mc
    container_name: rustfs-init
    entrypoint: >
      /bin/sh -c " until mc alias set rustfs http://rustfs:9000 admin password; do
        echo 'Waiting for RustFS...';
        sleep 2;
      done; mc ls rustfs/warehouse >/dev/null 2>&1 || mc mb rustfs/warehouse; "
    networks:
      - docker_net
    depends_on:
      rustfs:
        condition: service_healthy

  postgres:
    image: postgres:18.3
    hostname: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    networks:
      - docker_net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  spark_iceberg_kyuubi:
    build: ./docker/spark_iceberg_kyuubi
    container_name: spark_iceberg_kyuubi
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
    volumes:
      - ./data/notebooks:/var/lib/app/notebooks
    ports:
      - '8888:8888'
      - '7077:7077'
      - '8061:8061'
      - '8062:8062'
      - '10000:10000'
      - '10009:10009'
      - '18080:18080'
    networks:
      docker_net:
        aliases:
          - spark
    depends_on:
      rustfs:
        condition: service_healthy
      postgres:
        condition: service_healthy

  dagster-webserver:
    build: ./docker/dagster_dbt
    container_name: dagster-webserver
    networks:
      - docker_net
    ports:
      - 3000:3000
    volumes:
      - ./code/dagster_real_estate:/opt/dagster/dagster_home/
      - ./code/dbt_real_estate/bronze:/opt/dagster/dagster_home/src/dagster_real_estate/defs/bronze
      - ./code/dbt_real_estate/silver:/opt/dagster/dagster_home/src/dagster_real_estate/defs/silver
      - ./code/dbt_real_estate/gold:/opt/dagster/dagster_home/src/dagster_real_estate/defs/gold
    command: >
      sh -c "pip install -e /opt/dagster/dagster_home/ && dagster-webserver -h 0.0.0.0 -p 3000"

  dagster-daemon:
    build: ./docker/dagster_dbt
    container_name: dagster-daemon
    networks:
      - docker_net
    volumes:
      - ./code/dagster_real_estate:/opt/dagster/dagster_home/
      - ./code/dbt_real_estate/bronze:/opt/dagster/dagster_home/src/dagster_real_estate/defs/bronze
      - ./code/dbt_real_estate/silver:/opt/dagster/dagster_home/src/dagster_real_estate/defs/silver
      - ./code/dbt_real_estate/gold:/opt/dagster/dagster_home/src/dagster_real_estate/defs/gold
    command: >
      sh -c "pip install -e /opt/dagster/dagster_home/ && dagster-daemon run"

  trino:
    image: trinodb/trino:479
    container_name: trino
    volumes:
      - ./docker/trino/conf/catalog:/etc/trino/catalog
    ports:
      - 8060:8080
    networks:
      docker_net:
        aliases:
          - trino
    depends_on:
      postgres:
        condition: service_healthy
      rustfs:
        condition: service_healthy
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000

  metabase:
    image: metabase/metabase:v0.59.2.6
    hostname: metabase
    container_name: metabase
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=postgres
      - MB_DB_PORT=5432
      - MB_DB_USER=postgres
      - MB_DB_PASS=postgres
      - MB_DB_HOST=postgres
      - MB_JETTY_PORT=3030
    volumes:
      - ./docker/metabase/conf:/conf
    ports:
      - 3030:3030
    networks:
      - docker_net
    depends_on:
      postgres:
        condition: service_healthy

networks:
  docker_net:
    driver: bridge
