name: "silver"
version: "1.0.0"
config-version: 2

profile: "silver"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  silver:
    +schema: silver
    +materialized: table
    +table_type: iceberg
