version: 2

models:
  - name: gold_analytics_data
    description: "Table capturing real estate market advertises, including property sales and related metrics."
    columns:
      - name: sale_id
        description: "Unique identifier for the sale"
        tests:
          - not_null
      - name: account_id
        description: "Foreign key referencing dim_account"
        tests:
          - not_null
      - name: ad_id
        description: "Unique identifier for the ad"
        tests:
          - not_null
      - name: area
        description: "The area of the ad"
        tests:
          - not_null
      - name: area_name
        description: "The name of the area"
        tests:
          - not_null
      - name: category
        description: "The category of the ad"
        tests:
          - not_null
      - name: category_name
        description: "The name of the category"
        tests:
          - not_null
      - name: latitude
        description: "The latitude coordinate of the ad"
        tests:
          - not_null
      - name: longitude
        description: "The longitude coordinate of the ad"
        tests:
          - not_null
      - name: location
        description: "The location of the ad"
        tests:
          - not_null
      - name: date
        description: "The date of the listing"
        tests:
          - not_null
      - name: price
        description: "The price of the ad"
        tests:
          - not_null
      - name: region_name
        description: "The name of the region"
        tests:
          - not_null
      - name: rooms
        description: "The number of rooms in the property"
        tests:
          - not_null
      - name: size
        description: "The size of the property"
        tests:
          - not_null
      - name: type
        description: "The type of the property"
        tests:
          - not_null
      - name: year
        description: "The year of the listing"
        tests:
          - not_null
      - name: month
        description: "The month of the listing"
        tests:
          - not_null
      - name: quarter
        description: "The quarter of the listing"
        tests:
          - not_null
      - name: price_per_sqm
        description: "The price per square meter"
        tests:
          - not_null